# Package Overview
package_name: iris_model

# Data Files
training_data_file: iris.csv

# Variables
# The variable we are attempting to predict (cnt)
target: Name

pipeline_name: iris_model
pipeline_save_file: iris__model_output_v

# Features that will go inside processing pipeline
features:
  - SepalLength
  - SepalWidth
  - PetalLength
  - PetalWidth

# Features names
sepallength_var: SepalLength
sepalwidth_var: SepalWidth
petallength_var: PetalLength
petalwidth_var: PetalWidth

# Mappings for Ordinal categorical features
iris_mappings:
  Iris-setosa: 0
  Iris-versicolor: 1
  Iris-virginica: 2

# Set train/test split
test_size: 0.20

# Set the random seed
random_state: 42
evaluation_average: macro

# Alogrithm parameters
criterion: entropy
max_depth: 5
